export type LoungeRole = "member" | "admin";

export type LoungePersona = {
  id: string;
  name: string;
  city: string;
  color: string;
  role: LoungeRole;
};

const COLORS = [
  "bg-violet-500",
  "bg-sky-500",
  "bg-amber-500",
  "bg-emerald-500",
  "bg-rose-500",
  "bg-indigo-500",
  "bg-fuchsia-500",
  "bg-teal-500",
  "bg-orange-500",
  "bg-cyan-600",
  "bg-lime-600",
  "bg-pink-500",
];

const PEOPLE: [string, string][] = [
  ["Maya", "Nairobi"],
  ["Luis", "Manila"],
  ["Amina", "Lagos"],
  ["Theo", "Cape Town"],
  ["Priya", "Mumbai"],
  ["Noah", "Accra"],
  ["Lila", "Jakarta"],
  ["Ken", "Kisumu"],
  ["Fatima", "Kano"],
  ["Omar", "Mombasa"],
  ["Sana", "Lahore"],
  ["Diego", "Cebu"],
  ["Imani", "Dar es Salaam"],
  ["Ravi", "Hyderabad"],
  ["Chloe", "Johannesburg"],
  ["Yusuf", "Kampala"],
  ["Mei", "Quezon City"],
  ["Kwame", "Kumasi"],
  ["Elena", "Dublin"],
  ["Jamal", "Atlanta"],
  ["Nia", "Kisumu"],
  ["Arjun", "Bengaluru"],
  ["Sofia", "Lisbon"],
  ["Tunde", "Ibadan"],
  ["Hana", "Addis Ababa"],
  ["Victor", "Lusaka"],
  ["Amara", "Enugu"],
  ["Chen", "Singapore"],
  ["Zara", "Karachi"],
  ["Ibrahim", "Kigali"],
  ["Nora", "Toronto"],
  ["Samir", "Alexandria"],
  ["Leah", "Tel Aviv"],
  ["Biko", "Nakuru"],
  ["Ines", "Maputo"],
  ["Farah", "Doha"],
  ["Mateo", "Bogotá"],
  ["Aisha", "Zanzibar"],
  ["Jonah", "Harare"],
  ["Rina", "Surabaya"],
  ["Patrick", "Limerick"],
  ["Wanjiku", "Thika"],
  ["Hassan", "Mogadishu"],
  ["Tara", "Pune"],
  ["Eli", "Haifa"],
  ["Blessing", "Port Harcourt"],
  ["Nadia", "Casablanca"],
  ["Kojo", "Tamale"],
  ["Siti", "Kuala Lumpur"],
  ["Andre", "Recife"],
  ["Ruth", "Eldoret"],
  ["Pavel", "Prague"],
  ["Keisha", "Kingston"],
  ["Anil", "Chennai"],
  ["Marta", "Warsaw"],
  ["Femi", "Abeokuta"],
  ["Lina", "Amman"],
  ["George", "Limassol"],
  ["Adanna", "Onitsha"],
  ["Yara", "Beirut"],
  ["Seth", "Kumasi"],
  ["Irene", "Gaborone"],
  ["Hakim", "Tunis"],
  ["Joy", "Jinja"],
  ["Rashid", "Dodoma"],
  ["Camila", "Lima"],
  ["Olu", "Benin City"],
  ["Dina", "Suez"],
  ["Marcus", "Bridgetown"],
  ["Sable", "Windhoek"],
  ["Tariq", "Faisalabad"],
  ["Hope", "Monrovia"],
  ["Nabil", "Rabat"],
  ["Esther", "Lilongwe"],
  ["Kofi", "Takoradi"],
  ["Mina", "Isfahan"],
  ["Joel", "Suva"],
  ["Abena", "Cape Coast"],
  ["Rami", "Amman"],
  ["Tessa", "Perth"],
  ["Idris", "Jos"],
  ["Safiya", "Sokoto"],
  ["Luca", "Milan"],
  ["Zuri", "Nyeri"],
  ["Pedro", "Porto"],
  ["Khadija", "Marrakesh"],
  ["Ben", "Cardiff"],
  ["Aya", "Osaka"],
  ["Sam", "Brisbane"],
  ["Nala", "Arusha"],
  ["Beatrice", "Kisii"],
  ["Darnell", "Houston"],
  ["Esi", "Tema"],
  ["Farouk", "Khartoum"],
  ["Gita", "Kathmandu"],
  ["Hiro", "Sapporo"],
  ["Ife", "Abeokuta"],
  ["Jada", "Baltimore"],
  ["Kamau", "Nyahururu"],
  ["Leticia", "Guadalajara"],
  ["Mo", "Leeds"],
  ["Nneka", "Owerri"],
  ["Obinna", "Aba"],
  ["Pearl", "Freetown"],
  ["Quinton", "Durban"],
  ["Rahel", "Asmara"],
  ["Sadiq", "Kano"],
  ["Temi", "Abeokuta"],
  ["Uche", "Awka"],
  ["Valentina", "Medellín"],
  ["Wale", "Ilorin"],
  ["Xiomara", "San Pedro Sula"],
  ["Yemi", "Akure"],
  ["Zahra", "Shiraz"],
  ["Anika", "Dhaka"],
  ["Bruno", "Porto Alegre"],
  ["Celeste", "Montevideo"],
  ["Dalia", "Ramallah"],
  ["Emeka", "Nsukka"],
  ["Freya", "Bergen"],
  ["Gareth", "Swansea"],
  ["Halima", "Maiduguri"],
  ["Ismael", "Tanger"],
  ["Jengo", "Mwanza"],
  ["Karim", "Oran"],
  ["Laila", "Fes"],
  ["Mosi", "Kitwe"],
  ["Noura", "Muscat"],
  ["Otieno", "Homabay"],
  ["Paloma", "Seville"],
  ["Qadir", "Peshawar"],
  ["Reina", "Cebu City"],
  ["Salim", "Zanzibar City"],
  ["Talia", "Haifa"],
  ["Uma", "Kochi"],
  ["Vishal", "Ahmedabad"],
  ["Winnie", "Kitale"],
  ["Xavier", "Lyon"],
  ["Yasmin", "Alexandria"],
  ["Zakaria", "Fes"],
  ["Ayo", "Oshogbo"],
  ["Bianca", "São Paulo"],
  ["Cesar", "Quito"],
  ["Devi", "Jaipur"],
  ["Efe", "Warri"],
  ["Giselle", "Port of Spain"],
  ["Hamza", "Amman"],
  ["Ivana", "Zagreb"],
  ["Jibril", "Gombe"],
  ["Kendra", "Nassau"],
  ["Lok", "Hong Kong"],
  ["Marisol", "Tijuana"],
  ["Nnamdi", "Enugu"],
  ["Odette", "Kigali"],
  ["Palesa", "Maseru"],
  ["Quinn", "Halifax"],
  ["Rosario", "Asunción"],
  ["Siobhan", "Galway"],
  ["Tendai", "Bulawayo"],
  ["Ulises", "Monterrey"],
  ["Veda", "Mysuru"],
  ["Willem", "Stellenbosch"],
  ["Yolanda", "Harare"],
  ["Zane", "Auckland"],
  ["Adele", "Lyon"],
  ["Boris", "Sofia"],
  ["Chioma", "Aba"],
  ["Darius", "Vilnius"],
  ["Eshe", "Dodoma"],
  ["Felipe", "Valparaíso"],
  ["Greta", "Tallinn"],
  ["Hugo", "Antwerp"],
  ["Ilana", "Haifa"],
  ["Jomo", "Meru"],
  ["Katya", "Odessa"],
  ["Lemuel", "Cotonou"],
  ["Marwa", "Sfax"],
  ["Nkosi", "Soweto"],
  ["Ophelia", "Accra"],
  ["Pranav", "Nagpur"],
  ["Rania", "Amman"],
  ["Soren", "Aarhus"],
  ["Thandi", "Pietermaritzburg"],
  ["Vega", "Bilbao"],
  ["Wael", "Aleppo"],
  ["Xenia", "Thessaloniki"],
  ["Yarael", "Juba"],
  ["Zubair", "Multan"],
  ["Asha", "Malindi"],
  ["Binta", "Bamako"],
  ["Caleb", "Nairobi"],
  ["Dinawe", "Blantyre"],
  ["Elias", "Addis Ababa"],
  ["Farida", "Kano"],
  ["Gideon", "Kampala"],
  ["Hawa", "Conakry"],
  ["Isaiah", "Kingston"],
  ["Jamil", "Tripoli"],
  ["Khadra", "Hargeisa"],
  ["Liora", "Jerusalem"],
  ["Musa", "Kano"],
  ["Noor", "Karachi"],
  ["Oksana", "Lviv"],
  ["Piotr", "Kraków"],
  ["Rashida", "Tamale"],
  ["Sefu", "Morogoro"],
  ["Tamar", "Tbilisi"],
  ["Umar", "Kaduna"],
  ["Vivian", "Kumasi"],
  ["Wanjiru", "Nyeri"],
  ["Yusra", "Gaza"],
  ["Zola", "Gqeberha"],
];

export function loungeCrowd(): LoungePersona[] {
  return PEOPLE.map(([name, city], i) => ({
    id: `m${i + 1}`,
    name,
    city,
    color: COLORS[i % COLORS.length]!,
    role: "member",
  }));
}
